課題②提出
yuta10200831/11-docker-template pull request #2
Opened 2023-07-18 13:43 UTC by yuta10200831

## 作業対象
作業をした教材のURL or 作成したページのURLなどを記載する
[作業をした教材のURL]
https://www.notion.so/11-580d060ed9244c65b003dea4b154edd2
[作成したページのURL(index.php)]
<img width="1625" alt="スクリーンショット 2023-07-18 22 40 04" src="https://github.com/yuta10200831/11-docker-template/assets/124555669/4f81bed7-9950-4f95-9b27-46381250017f">

## 作業詳細
$array 配列の中で3の倍数の値の内、最大値であるものを出力する
(期待する出力)
12
9
3
<img width="1647" alt="スクリーンショット 2023-07-18 22 40 15" src="https://github.com/yuta10200831/11-docker-template/assets/124555669/3b6c222d-e308-466c-bbb4-d21e9e410e2e">

2023-07-19 08:55 UTC, KatsuyaTanaka95 requested changes
レビューさせていただきました！
ご修正をお願いいたします！🙆🙋😊🌟💫

2023-07-19 08:55 UTC, KatsuyaTanaka95 commented on src/public/Q2.php
> +        }
ガード節にしましょう！！

2023-07-19 08:55 UTC, KatsuyaTanaka95 commented on src/public/Q2.php
> +    $maxMultipleOfThree = null;
ここは、null ではなく、 0を代入しましょう！！！

2023-07-19 12:46 UTC, yuta10200831 commented on src/public/Q2.php
> +    $maxMultipleOfThree = null;
修正しました！

2023-07-19 13:11 UTC, yuta10200831 commented on src/public/Q2.php
> +        }
修正しました！

2023-07-19 13:13 UTC, yuta10200831 commented
修正しました！
ガード節を用いてif文を書き換えました。
ご確認宜しくお願いします！！

2023-07-20 07:18 UTC, KatsuyaTanaka95 requested changes
レビューさせていただきました！
ご修正をお願いいたします！🙆🙋😊🌟💫

2023-07-20 07:18 UTC, KatsuyaTanaka95 commented on src/public/Q2.php
> +        }
$maxMultipleOfThree === null　は必要ない気がします！？
必要なものでしたらすみません！😭😱

2023-08-17 14:41 UTC, yuta10200831 commented on src/public/Q2.php
> +        }
修正済み

2023-08-17 14:43 UTC, yuta10200831 commented
修正しました！
$maxMultipleOfThree === null←いりませんでした。
改めて出力結果を送付致します。
<img width="1707" alt="スクリーンショット 2023-08-17 23 43 01" src="https://github.com/yuta10200831/11-docker-template/assets/124555669/3720339c-ac4a-421f-a220-f2ccaad9c40b">

2023-08-18 06:18 UTC, KatsuyaTanaka95 approved these changes
ご修正ありがとうございます！
mergeしちゃいましょ〜🙆🙋😊🌟💫

2023-08-18 11:23 UTC, merged